package com.quince.lawyeraiassistant.common.exception;

public enum ErrorCode {

    VALIDATION_ERROR,

    MISSING_REQUEST_PARAMETER,

    INVALID_ARGUMENT,

    AI_CONTENT_REJECTED,

    KNOWLEDGE_BASE_INITIALIZATION_ERROR,

    KNOWLEDGE_BASE_DOCUMENT_LOAD_ERROR,

    KNOWLEDGE_BASE_VECTOR_WRITE_ERROR,

    KNOWLEDGE_BASE_VECTOR_SEARCH_ERROR,

    INTERNAL_SERVER_ERROR
}